const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '..', 'server', '.env');
if (fs.existsSync(envPath)) {
  console.log(`[bootstrap] server/.env already exists at ${envPath}`);
  process.exit(0);
}

const content = `# Auto-generated by scripts/bootstrap.cjs\n\n# Feature flags\nENABLE_JOBS=true\nENABLE_ML=true\n\n# Redis / Jobs\nREDIS_URL=redis://localhost:6379\nJOB_BATCH=20\nJOB_ATTEMPTS=2\nJOB_BACKOFF_MS=500\n\n# ML service base\nML_BASE_URL=http://localhost:5001\n\n# Providers (optional)\nNEWS_API_KEY=\nTRENDLYNE_EMAIL=\nTRENDLYNE_PASSWORD=\nALPHAVANTAGE_API_KEY=\n\n# Ticker overrides\nTICKER_YAHOO_SUFFIX=.NS\n\n# Bases\nSELF_BASE_URL=http://localhost:4010\nSERVER_BASE_URL=http://localhost:4010\n`;

fs.writeFileSync(envPath, content, 'utf8');
console.log(`[bootstrap] Wrote minimal env to ${envPath}`);

